src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Category;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100, unique: true)]
    private ?string $name = null;

    #[ORM\Column(length: 100, unique: true)]
    private ?string $slug = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $abstract = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?int $quantity = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column]
    private ?int $min_players = null;

    #[ORM\Column(nullable: true)]
    private ?int $max_players = null;

    #[ORM\Column(nullable: true)]
    private ?int $minimum_age = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $duration = null;

    #[ORM\Column(length: 45, nullable: true)]
    private ?string $editor = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $theme = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $mecanism = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    #[ORM\OneToMany(mappedBy: 'product_id', targetEntity: OrderDetail::class)]
    private Collection $orderDetails;

    #[ORM\Column(length: 45)]
    private ?string $img1 = null;

    #[ORM\Column(length: 45, nullable: true)]
    private ?string $img2 = null;

    #[ORM\Column(length: 45, nullable: true)]
    private ?string $img3 = null;

    public function __construct()
    {
        $this->orderDetails = new ArrayCollection();
        $this->images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getAbstract(): ?string
    {
        return $this->abstract;
    }

    public function setAbstract(string $abstract): self
    {
        $this->abstract = $abstract;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getMinPlayers(): ?int
    {
        return $this->min_players;
    }

    public function setMinPlayers(int $min_players): self
    {
        $this->min_players = $min_players;

        return $this;
    }

    public function getMaxPlayers(): ?int
    {
        return $this->max_players;
    }

    public function setMaxPlayers(?int $max_players): self
    {
        $this->max_players = $max_players;

        return $this;
    }

    public function getMinimumAge(): ?int
    {
        return $this->minimum_age;
    }

    public function setMinimumAge(?int $minimum_age): self
    {
        $this->minimum_age = $minimum_age;

        return $this;
    }

    public function getDuration(): ?\DateTimeInterface
    {
        return $this->duration;
    }

    public function setDuration(?\DateTimeInterface $duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    public function getEditor(): ?string
    {
        return $this->editor;
    }

    public function setEditor(?string $editor): self
    {
        $this->editor = $editor;

        return $this;
    }

    public function getTheme(): ?string
    {
        return $this->theme;
    }

    public function setTheme(?string $theme): self
    {
        $this->theme = $theme;

        return $this;
    }

    public function getMecanism(): ?string
    {
        return $this->mecanism;
    }

    public function setMecanism(?string $mecanism): self
    {
        $this->mecanism = $mecanism;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection<int, OrderDetail>
     */
    public function getOrderDetails(): Collection
    {
        return $this->orderDetails;
    }

    public function addOrderDetail(OrderDetail $orderDetail): self
    {
        if (!$this->orderDetails->contains($orderDetail)) {
            $this->orderDetails->add($orderDetail);
            $orderDetail->setProductId($this);
        }

        return $this;
    }

    public function removeOrderDetail(OrderDetail $orderDetail): self
    {
        if ($this->orderDetails->removeElement($orderDetail)) {
            // set the owning side to null (unless already changed)
            if ($orderDetail->getProductId() === $this) {
                $orderDetail->setProductId(null);
            }
        }

        return $this;
    }

    public function getImg1(): ?string
    {
        return $this->img1;
    }

    public function setImg1(string $img1): self
    {
        $this->img1 = $img1;

        return $this;
    }

    public function getImg2(): ?string
    {
        return $this->img2;
    }

    public function setImg2(?string $img2): self
    {
        $this->img2 = $img2;

        return $this;
    }

    public function getImg3(): ?string
    {
        return $this->img3;
    }

    public function setImg3(?string $img3): self
    {
        $this->img3 = $img3;

        return $this;
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Form\ProductType;
use App\Repository\ProductRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\String\Slugger\AsciiSlugger;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ProductController extends AbstractController
{
    #[Route('/products', name: 'products')]
    public function index(ProductRepository $productRepository): Response
    {
        $products = $productRepository->findAll();
        return $this->render('product/index.html.twig', [
            'products' => $products,
        ]);
    }

    #[Route('/product/{slug}', name: 'product_show')]
    public function show($slug, ProductRepository $productRepository): Response
    {
        $product = $productRepository->findOneBy(['slug' => $slug]);
        return $this->render('product/show.html.twig', [
            'product' => $product
        ]);
    }

    #[Route('/admin/products', name: 'admin_products')]
    public function adminList(ProductRepository $productRepository): Response
    {
        $products = $productRepository->findAll();
        return $this->render('product/adminList.html.twig', [
            'products' => $products
        ]);
    }
    
    #[Route('/admin/product/create', name: 'product_create')]
    public function create(Request $request, ProductRepository $productRepository, ManagerRegistry $managerRegistry): Response
    {
        $product = new Product(); // création d'un nouveau produit
        $form = $this->createForm(ProductType::class, $product); // création d'un formulaire avec en paramètre le nouveau produit
        $form->handleRequest($request); // gestionnaire de requêtes HTTP

        if ($form->isSubmitted() && $form->isValid()) { // vérifie si le formulaire a été soumis et est valide

            $products = $productRepository->findAll(); // récupère tous les produits en base de données
            $productNames = []; // initialise un tableau pour les noms de produits
            foreach ($products as $product) { // pour chaque produit récupéré
                $productNames[] = strtolower($product->getName()); // stocke le nom du produit dans le tableau
            }
            if (in_array(strtolower($form['name']->getData()), $productNames)) { // vérifie qsi le nom du produit à créé n'est pas déjà utilisé en base de données
                $this->addFlash('danger', 'Le produit n\'a pas pu être créé : le nom de produit est déjà utilisé');
                return $this->redirectToRoute('admin_products');
            }

            $infoImg1 = $form['img1']->getData(); // récupère les données du champ img1 du formulaire

            if (empty($infoImg1)) { // vérifie la présence de l'image principale dans le formulaire
                $this->addFlash('danger', 'Le produit n\'a pas pu être créé : l\'image principale est obligatoire mais n\'a pas été renseignée');
                return $this->redirectToRoute('admin_products');
            }

            $extensionImg1 = $infoImg1->guessExtension(); // récupère l'extension de fichier de l'image 1
            $nomImg1 = time() . '-1.' . $extensionImg1; // crée un nom de fichier unique pour l'image 1
            $infoImg1->move($this->getParameter('product_image_dir'), $nomImg1); // télécharge le fichier dans le dossier adéquat
            $product->setImg1($nomImg1); // définit le nom de l'image à mettre ne base de données

            $infoImg2 = $form['img2']->getData();
            if ($infoImg2 !== null) {
                $extensionImg2 = $infoImg2->guessExtension();
                $nomImg2 = time() . '-2.' . $extensionImg2;
                $infoImg2->move($this->getParameter('product_image_dir'), $nomImg2);
                $product->setImg2($nomImg2);
            }

            $infoImg3 = $form['img3']->getData();
            if ($infoImg3 !== null) {
                $extensionImg3 = $infoImg3->guessExtension();
                $nomImg3 = time() . '-3.' . $extensionImg3;
                $infoImg3->move($this->getParameter('product_image_dir'), $nomImg3);
                $product->setImg3($nomImg3);
            }

            $slugger = new AsciiSlugger();
            $product->setSlug(strtolower($slugger->slug($form['name']->getData()))); // génère un slug à partir du titre renseigné dans le formulaire
            $product->setCreatedAt(new \DateTimeImmutable());

            $manager = $managerRegistry->getManager();
            $manager->persist($product);
            $manager->flush();

            $this->addFlash('success', 'Le produit a bien été créé'); // message de succès
            return $this->redirectToRoute('admin_products');
        }

        return $this->render('product/form.html.twig', [
            'productForm' => $form->createView()
        ]);
    }

    #[Route('/admin/product/update/{id}', name: 'product_update')]
    public function update(Product $product, ProductRepository $productRepository, Request $request, ManagerRegistry $managerRegistry): Response
    {
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            // $products = $productRepository->findAll(); // récupère tous les produits en base de données
            // $productNames = []; // initialise un tableau pour les noms de produits
            // foreach ($products as $product) { // pour chaque produit récupéré
            //     $productNames[] = $product->getName(); // stocke le nom du produit dans le tableau
            // }
            // if (in_array($form['name']->getData(), $productNames)) { // vérifie si le nom du produit à créer n'est pas déjà utilisé en base de données
            //     $this->addFlash('danger', 'Le produit n\'a pas pu être modifié : le nom de produit est déjà utilisé');
            //     return $this->redirectToRoute('admin_products');
            // }

            $infoImg1 = $form['img1']->getData(); // récupère les informations de l'image 1 dans le formulaire
            if ($infoImg1 !== null) { // s'il y a bien une image donnée dans le formulaire
                $oldImg1Name = $product->getImg1(); // récupère le nom de l'ancienne image
                $oldImg1Path = $this->getParameter('product_image_dir') . '/' . $oldImg1Name; // récupère le chemin de l'ancienne image 1
                if (file_exists($oldImg1Path)) {
                    unlink($oldImg1Path); // supprime l'ancienne image 1
                }
                $extensionImg1 = $infoImg1->guessExtension(); // récupère l'extension de fichier de l'image 1
                $nomImg1 = time() . '-1.' . $extensionImg1; // crée un nom de fichier unique pour l'image 1
                $infoImg1->move($this->getParameter('product_image_dir'), $nomImg1); // télécharge le fichier dans le dossier adéquat
                $product->setImg1($nomImg1); // définit le nom de l'image à mettre ne base de données
            }

            $infoImg2 = $form['img2']->getData();
            if ($infoImg2 !== null) {
                $oldImg2Name = $product->getImg2(); // récupère le nom de l'ancienne image 2 (en bdd)
                if ($oldImg2Name !== null) { // vérifie s'il y a une image 2 en base de données
                    $oldImg2Path = $this->getParameter('product_image_dir') . '/' . $oldImg2Name;
                    if (file_exists($oldImg1Path)) {
                        unlink($oldImg2Path);
                    }
                }
                $extensionImg2 = $infoImg2->guessExtension();
                $nomImg2 = time() . '-2.' . $extensionImg2;
                $infoImg2->move($this->getParameter('product_image_dir'), $nomImg2);
                $product->setImg2($nomImg2);
            }

            $infoImg3 = $form['img3']->getData();
            if ($infoImg3 !== null) {
                $oldImg3Name = $product->getImg3();
                if ($oldImg3Name !== null) {
                    $oldImg3Path = $this->getParameter('product_image_dir') . '/' . $oldImg3Name;
                    if (file_exists($oldImg1Path)) {
                        unlink($oldImg3Path);
                    }
                }
                $extensionImg3 = $infoImg3->guessExtension();
                $nomImg3 = time() . '-3.' . $extensionImg3;
                $infoImg3->move($this->getParameter('product_image_dir'), $nomImg3);
                $product->setImg3($nomImg3);
            }

            $slugger = new AsciiSlugger();
            $product->setSlug(strtolower($slugger->slug($form['name']->getData())));
            $manager = $managerRegistry->getManager();
            $manager->persist($product);
            $manager->flush();

            $this->addFlash('success', 'Le produit a bien été modifié');
            return $this->redirectToRoute('admin_products');
        }

        return $this->render('product/form.html.twig', [
            'productForm' => $form->createView()
        ]);
    }

    #[Route('/admin/product/delete/{id}', name: 'product_delete')]
    public function delete(Product $product, ManagerRegistry $managerRegistry): Response
    {
        $img1path = $this->getParameter('product_image_dir') . '/' . $product->getImg1();
        if (file_exists($img1path)) {
            unlink($img1path);
        }

        if ($product->getImg2() !== null) {
            $img2path = $this->getParameter('product_image_dir') . '/' . $product->getImg2();
            if (file_exists($img2path)) {
                unlink($img2path);
            }
        }
        
        if ($product->getImg3() !== null) {
            $img3path = $this->getParameter('product_image_dir') . '/' . $product->getImg3();

templates/product/adminList.html.twig
{% extends "baseAdmin.html.twig" %}

{% block title %}produits{% endblock %}

{% block body %}

    <h1 class="pb-5">Liste des produits</h1>

    <table class="table table-hover table-sm texxt-center align-middle text-center">
        <thead>
            <tr>
                <th>N°</th>
                <th>Nom</th>
                <th>Prix</th>
                <th>Catégorie</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for product in products|reverse %}
                <tr>
                    <td>{{ loop.revindex }}</td>
                    <td class="text-start"><img src="{{ asset('img/product/' ~ product.img1) }}" alt="image principale du jeu {{ product.name }}" class="pe-3"> {{ product.name }}</td>
                    <td>{{ product.price|number_format(2, ',', ' ') }} €</td>
                    <td>{{ product.category.name }}</td>
                    <td>
                        <a href="{{ path('product_update', {'id': product.id}) }}"><i class="bi bi-pencil-square text-primary"></i></a>
                        <a href="{{ path('product_delete', {'id': product.id}) }}"><i class="bi bi-trash3 text-danger"></i></a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="text-end mt-4">
        <a href="{{ path('product_create') }}" class="btn btn-success">Ajouter un produit</a>
    </div>
    
{% endblock %}

templates/product/form.html.twig
{% extends "baseAdmin.html.twig" %}

{% block title %}{{ app.request.attributes.get('_route') == 'product_create' ? 'création' : 'modification' }} produit{% endblock %}

{% block body %}

    <h1 class="mb-5">{{ app.request.attributes.get('_route') == 'product_create' ? 'Créer' : 'Modifier' }} un produit</h1>

    {# {{ form(productForm) }} #}

    {{ form_start(productForm) }}

        <div class="row">
            <div class="col-6">
                {# {{ form_row(productForm.name) }} #}
                {{ form_label(productForm.name, 'Nom') }}
                {{ form_errors(productForm.name) }}
                {{ form_widget(productForm.name, {
                    'attr': {
                        'placeholder': 'Ex.: David'
                    }
                }) }}
                {{ form_help(productForm.name) }}
            </div>
            <div class="col-3">
                {{ form_row(productForm.quantity, {
                    'label': 'Quantité',
                    'attr': {
                        'placeholder': 'Ex.: 12'
                    }
                }) }}
            </div>
            <div class="col-3">
                {{ form_row(productForm.price, {
                    'label': 'Prix (en €)',
                    'attr': {
                        'placeholder': 'Ex.: 123.45'
                    }
                }) }}
            </div>
        </div>

        <div class="row">
            <div class="col-6">
                {{ form_row(productForm.abstract, {
                    'label': 'Résumé',
                    'attr': {
                        'placeholder': 'Ex.: Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita provident et quod. Vero aliquid praesentium earum eos, facilis doloremque tempora ab quidem incidunt ! Ea, dignissimos. Quas sed modi sapiente dolorem ?'
                    }
                }) }}
            </div>
            <div class="col-6">
                {{ form_row(productForm.description, {
                    'label': 'Description',
                    'attr': {
                        'placeholder': 'Ex.: Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita provident et quod. Vero aliquid praesentium earum eos, facilis doloremque tempora ab quidem incidunt ! Ea, dignissimos. Quas sed modi sapiente dolorem ?'
                    }
                }) }}
            </div>
        </div>

        <div class="row">
            <div class="col">
                {{ form_row(productForm.min_players, {
                    'label': 'Joueurs minimum',
                    'attr': {
                        'placeholder': 'Ex.: 1'
                    }
                }) }}
            </div>
            <div class="col">
                {{ form_row(productForm.max_players, {
                    'label': 'Joueurs maximum',
                    'attr': {
                        'placeholder': 'Ex.: 2'
                    }
                }) }}
            </div>
            <div class="col">
                {{ form_row(productForm.minimum_age, {
                    'label': 'Âge minimum',
                    'attr': {
                        'placeholder': 'Ex.: 3'
                    }
                }) }}
            </div>
            <div class="col">
                {{ form_row(productForm.duration, {
                    'label': 'Durée'
                }) }}
            </div>
            <div class="col">
                {{ form_row(productForm.editor, {
                    'label': 'Éditeur',
                    'attr': {
                        'placeholder': 'Ex.: David'
                    }
                }) }}
            </div>
            <div class="col">
                {{ form_row(productForm.category, {
                    'label': 'Catégorie',
                    'placeholder': '-- sélectionner --'
                }) }}
            </div>
        </div>

        <div class="row">
            <div class="col-6">
                {{ form_row(productForm.theme, {
                    'label': 'Thème(s)',
                    'attr': {
                        'placeholder': 'Ex.: France, guerre'
                    }
                }) }}
            </div>
            <div class="col-6">
                {{ form_row(productForm.mecanism, {
                    'label': 'Mécanisme(s)',
                    'attr': {
                        'placeholder': 'Ex.: placement, draft'
                    }
                }) }}
            </div>
        </div>

        <div class="row">
            <div class="col-4">
                {{ form_row(productForm.img1, {
                    'label': 'Image principale (obligatoire)'
                }) }}
            </div>
            <div class="col-4">
                {{ form_row(productForm.img2, {
                    'label': 'Image secondaire 1 (optionnel)'
                }) }}
            </div>
            <div class="col-4">
                {{ form_row(productForm.img3, {
                    'label': 'Image secondaire 2 (optionnel)'
                }) }}
            </div>
        </div>

        <div class="row">
            <div class="col-12 text-end my-3">
                <a href="{{ path('admin_products')}}" class="btn btn-outline-danger me-3">Annuler</a>
                {# app.request.attributes.get('_route') pour récupérer la route actuelle #}
                <button class="btn btn-success">{{ app.request.attributes.get('_route') == 'product_create' ? 'Créer' : 'Modifier' }} </button>
            </div>
        </div>

    {{ form_end(productForm) }}

{% endblock %}

templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block description %}Liste complète des produits de votre boutique Table Top Games{% endblock %}

{% block title %}produits{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/product.css') }}">
{% endblock %}

{% block h1 %}Produits{% endblock %}

{% block body %}

    {% for product in products %}
        <div class="col-md-6 col-lg-4 col-xl-3 p-3">
            <div class="card">
                <img src="{{ asset('img/product/' ~ product.img1) }}" class="card-img-top p-3" alt="image principale du jeu {{ product.name }}">
                {% if product.createdAt|date('Y-m-d') >= "now"|date_modify("-20 day")|date('Y-m-d') %}
                    <span class="new_product">Nouveauté</span>
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{ product.name }}</h5>
                    <p class="card-text">{{ product.abstract|u.truncate(70, '...', false) }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{ product.minPlayers }} à {{ product.maxPlayers }} joueur(s)</li>
                    <li class="list-group-item">{{ product.price|number_format(2, ',', ' ') }} €</li>
                </ul>
                <div class="card-body text-center">
                    <a href="{{ path('product_show', {'slug': product.slug}) }}" class="card-link btn btn-outline-primary">Détails</a>
                    <a href="{{ path('cart_add', {'id': product.id}) }}" class="card-link btn btn-{{ product.quantity != 0 ? 'success' : 'danger disabled' }}"><i class="bi bi-cart-plus-fill"></i></a>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock %}

templates/product/searchForm.html.twig
{{ form_start(searchForm) }}
    {{ form_widget(searchForm.search) }}
    <button type="submit" class="btn btn-success">Chercher</button>
{{ form_end(searchForm) }}

templates/product/searchResult.html.twig
{% extends "base.html.twig" %}

{% block description %}Résultats de la recherche {{ searchedValue }}{% endblock %}

{% block title %}recherche{% endblock %}

{% block breadcrump %}
     / 
    <a href="{{ path('products') }}">Produits</a>
     / 
    Recherche
     / 
    {{ searchedValue }}
{% endblock %}

{% block h1 %}Recherche{% endblock %}

{% block body %}

    <p>Recherche : {{ searchedValue }}</p>
    {% for product in products %}
        {{ product.name }}<br>
    {% else %}
        <p class="text-center">Aucun réslutat</p>
    {% endfor %}

{% endblock %}

templates/product/show.html.twig
{% extends "base.html.twig" %}

{% block description %}{{ product.abstract|u.truncate(157, '...') }}{% endblock %}

{% block title %}{{ product.name }}{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/product.css') }}">
{% endblock %}

{% block h1 %}{{ product.name }}{% endblock %}

{% block body %}

    <div class="col-md-8 col-lg-4 offset-md-2 offset-lg-1">
        <div class="row mb-4">
            <img src="{{ asset('img/product/' ~ product.img1) }}" alt="photo principale du jeu {{ product.name }}" class="w-100 mainImg">
        </div>
        <div class="row">
            <div class="col-4">
                <img src="{{ asset('img/product/' ~ product.img1) }}" alt="photo secondaire du jeu {{ product.name }}" class="w-100">
            </div>
            {% if product.img2 != null %}
                <div class="col-4">
                    <img src="{{ asset('img/product/' ~ product.img2) }}" alt="photo secondaire du jeu {{ product.name }}" class="w-100">
                </div>
            {% endif %}
            {% if product.img3 != null %}
                <div class="col-4">
                    <img src="{{ asset('img/product/' ~ product.img3) }}" alt="photo secondaire du jeu {{ product.name }}" class="w-100">
                </div>
            {% endif %}
        </div>
    </div>
    <div class="col-md-8 col-lg-5 offset-md-2 offset-lg-1 mt-5 mt-lg-0">
        <h2>{{ product.name }}</h2>
        <hr class="text-secondary">
        <div class="my-4">
            <p class="fs-3">
                {{ product.price|number_format(2, ',', ' ') }} €
                {% if product.quantity != 0 %}
                    <span class="fs-4 text-success">En stock</span>
                {% else %}
                    <span class="fs-4 text-danger">Rupture de stock</span>
                {% endif %}
            </p>
            <p>{{ product.abstract }}</p>
            <p>
                <span class="badge bg-secondary p-2 me-2">{{ product.minPlayers }} à {{ product.maxPlayers }} joueur(s)</span>
                <span class="badge bg-secondary p-2 me-2">Environ {{ product.duration|date('h') > 0 ? product.duration|date('h') * 60 + product.duration|date('i') : product.duration|date('i') }} minutes</span>
                <span class="badge bg-secondary p-2">À partir de {{ product.minimumAge }} an(s)</span>
            </p>
        </div>
        <hr class="text-secondary">
        <div class="my-4">
            <p>Éditeur : {{ product.editor }}</p>
            <p>Thème(s) : {{ product.theme }}</p>
            <p>Mécanisme(s) : {{ product.mecanism }}</p>
        </div>
        <hr class="text-secondary">
        <div class="mt-4">
            <p class="text-end">
                <a href="{{ path('cart_add', {'id': product.id}) }}" class="btn btn-{{ product.quantity != 0 ? 'success' : 'danger disabled' }}">Ajouter au panier</a>
            </p>
        </div>
    </div>
    <div class="row mt-5">
        <div class="col-md-8 col-lg-10 offset-md-2 offset-lg-1">
            <h2>Description</h2>
            <p>{{ product.description }}</p>
        </div>
    </div>

{% endblock %}